name: alethic-ism-processor-gemini
channels:
  - file:///Users/kasrarasaee/miniconda3/envs/local_channel
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - python-dotenv
  - psycopg2
  - pyyaml
  - pydantic
  - pydantic-core
  - google-generativeai
  - redis-py
  - nats-py
  - mako
  - restrictedpython
  - alethic-ism-core
  - alethic-ism-db
